name: Deploy Overleaf

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Upgrade npm
      run: npm install -g npm@11.4.2

    - name: Install dependencies
      run: |
        npm ci --ignore-scripts
        npx patch-package || true

    - name: Run linting (optional)
      run: |
        if npm run lint --if-present; then
          echo "Linting completed successfully"
        else
          echo "Linting failed or not available, continuing..."
        fi

    - name: Run tests (optional)
      run: |
        echo "Tests would run here when available"
        echo "Build successful!"

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server-ce
        file: ./server-ce/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    environment:
      name: production
      url: ${{ steps.deploy.outputs.webapp-url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production
      id: deploy
      run: |
        echo "This step would deploy to your production environment"
        echo "You can integrate with services like:"
        echo "- AWS ECS/Fargate"
        echo "- Google Cloud Run"
        echo "- Azure Container Instances"
        echo "- DigitalOcean App Platform"
        echo "- Your own Docker host"
        echo "webapp-url=https://your-domain.com" >> $GITHUB_OUTPUT

    - name: Deployment notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
